apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:metrics-server
  # namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/stats
      - nodes
    verbs:
      - get
      - list